// AAA CORE ENGINE - MAIN.JS
// Implements: World Streaming, Physics Loop, AI Traffic, Dialogue System

class Game {
    constructor() {
        this.scene = null;
        this.camera = null;
        this.renderer = null;
        this.clock = new THREE.Clock();

        // Systems
        this.player = null;
        this.world = null;
        this.traffic = null;
        this.interaction = null;

        // State
        this.currentState = WORLD_DATA.narrative.initialState;
        this.currentRegion = WORLD_DATA.regions[WORLD_DATA.narrative.states[this.currentState].region];

        this.init();
    }

    init() {
        this.setupThreeJS();
        this.setupSystems();
        this.setupEventListeners();
        this.animate();

        // Initial HUD update
        this.updateHUD(WORLD_DATA.narrative.states[this.currentState].objective);

        // Start Ambience
        console.log(`Region Loaded: ${this.currentRegion.name}`);
    }

    setupThreeJS() {
        this.scene = new THREE.Scene();
        this.updateEnvironment(this.currentRegion);

        this.camera = new THREE.PerspectiveCamera(70, window.innerWidth / window.innerHeight, 0.1, 1000);
        this.camera.rotation.order = 'YXZ';

        this.renderer = new THREE.WebGLRenderer({ antialias: false, powerPreference: "high-performance" });
        this.renderer.setSize(window.innerWidth, window.innerHeight);
        this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
        document.body.appendChild(this.renderer.domElement);
    }

    updateEnvironment(region) {
        this.scene.background = new THREE.Color(region.skyColor);
        this.scene.fog = new THREE.FogExp2(region.fogColor, region.fogDensity);

        // Lighting
        this.scene.clear(); // Careful, this wipes everything.
        // In a real engine we'd update existing lights. For now, clear is safer for drastic region changes.
        // BUT we need to persist Player.
        // Re-adding lights:
        const ambient = new THREE.AmbientLight(region.lightColor, 0.2);
        this.scene.add(ambient);

        const moon = new THREE.DirectionalLight(0xffffff, 0.5);
        moon.position.set(50, 100, 50);
        this.scene.add(moon);

        // Ground is generated by World class
    }

    setupSystems() {
        this.player = new Player(this.camera, this.scene);
        this.world = new World(this.scene, this.currentRegion);
        this.traffic = new TrafficSystem(this.scene, this.currentRegion, this.world.roads);
        this.interaction = new InteractionSystem(this.camera, this.scene, this);
    }

    setupEventListeners() {
        window.addEventListener('resize', () => {
            this.camera.aspect = window.innerWidth / window.innerHeight;
            this.camera.updateProjectionMatrix();
            this.renderer.setSize(window.innerWidth, window.innerHeight);
        });

        document.addEventListener('click', () => {
            document.body.requestPointerLock();
        });
    }

    updateHUD(text) {
        const objective = document.getElementById('objective-text');
        if(objective) objective.innerText = `// ${text}`;
    }

    animate() {
        requestAnimationFrame(() => this.animate());

        const delta = Math.min(this.clock.getDelta(), 0.1); // Cap delta to prevent physics explosions

        this.player.update(delta, this.world.collidables);
        this.traffic.update(delta, this.player.position);
        this.interaction.update();

        this.renderer.render(this.scene, this.camera);
    }

    advanceStory() {
        const stateData = WORLD_DATA.narrative.states[this.currentState];
        if (stateData.nextState && WORLD_DATA.narrative.states[stateData.nextState]) {
            this.currentState = stateData.nextState;
            const newState = WORLD_DATA.narrative.states[this.currentState];

            // Region Change?
            if (newState.region !== this.currentRegion.id) {
                this.currentRegion = WORLD_DATA.regions[newState.region];
                this.updateEnvironment(this.currentRegion);
                this.world.regenerate(this.currentRegion);
                this.traffic.regenerate(this.currentRegion, this.world.roads);
                // Teleport player to safe start of new region
                this.player.resetPosition();
            }

            this.updateHUD(newState.objective);
            console.log(`Story Advanced: ${this.currentState}`);
        }
    }
}

// --- PHYSICS & PLAYER CONTROLLER ---

class Player {
    constructor(camera, scene) {
        this.camera = camera;
        this.scene = scene;
        this.position = camera.position;
        this.velocity = new THREE.Vector3();
        this.direction = new THREE.Vector3();

        this.canJump = false;
        this.isSprinting = false;

        this.keys = { w: false, a: false, s: false, d: false, space: false, shift: false };

        this.capsuleHeight = 2.0;
        this.capsuleRadius = 0.5;

        this.resetPosition();
        this.bindInput();
    }

    resetPosition() {
        this.position.set(0, 5, 0); // Drop in
        this.velocity.set(0, 0, 0);
    }

    bindInput() {
        document.addEventListener('keydown', (e) => this.onKey(e, true));
        document.addEventListener('keyup', (e) => this.onKey(e, false));
        document.addEventListener('mousemove', (e) => this.onMouseMove(e));
    }

    onKey(e, pressed) {
        const key = e.key.toLowerCase();
        if (this.keys.hasOwnProperty(key)) this.keys[key] = pressed;
        if (e.code === 'Space') this.keys.space = pressed;
        if (e.key === 'Shift') this.keys.shift = pressed;
    }

    onMouseMove(e) {
        if (document.pointerLockElement !== document.body) return;
        this.camera.rotation.y -= e.movementX * 0.002;
        this.camera.rotation.x -= e.movementY * 0.002;
        this.camera.rotation.x = Math.max(-Math.PI/2, Math.min(Math.PI/2, this.camera.rotation.x));
    }

    update(delta, collidables) {
        if (document.pointerLockElement !== document.body) return;

        const config = WORLD_DATA.config;

        // Friction (Air resistance)
        this.velocity.x -= this.velocity.x * 10.0 * delta;
        this.velocity.z -= this.velocity.z * 10.0 * delta;

        // Gravity
        this.velocity.y -= config.gravity * delta;

        // Movement Input - Decouple from Camera Pitch
        // We need the forward vector projected onto the XZ plane
        const forward = new THREE.Vector3(0, 0, -1).applyQuaternion(this.camera.quaternion);
        forward.y = 0;
        forward.normalize();

        const right = new THREE.Vector3(1, 0, 0).applyQuaternion(this.camera.quaternion);
        right.y = 0;
        right.normalize();

        const moveZ = Number(this.keys.w) - Number(this.keys.s);
        const moveX = Number(this.keys.d) - Number(this.keys.a);

        const speed = this.keys.shift ? config.playerSpeed * config.sprintMultiplier : config.playerSpeed;

        if (moveZ !== 0 || moveX !== 0) {
            // Combine vectors
            this.direction.copy(forward).multiplyScalar(moveZ).add(right.multiplyScalar(moveX)).normalize();

            // Apply force to velocity (instead of direct translation) for smoother physics feel
            // But for tight controls, direct velocity manipulation is often better in simple engines
            this.velocity.x += this.direction.x * speed * 10.0 * delta; // Accelerate
            this.velocity.z += this.direction.z * speed * 10.0 * delta;
        }

        // Apply Velocity to Position manually (don't use translateX/Z as they are local to rotated camera)
        this.position.x += this.velocity.x * delta;
        this.position.z += this.velocity.z * delta;
        this.position.y += this.velocity.y * delta;

        // Ground/Collision Check (Simplified AABB)
        // Check floor
        if (this.position.y < this.capsuleHeight) {
            this.position.y = this.capsuleHeight;
            this.velocity.y = 0;
            this.canJump = true;
        }

        // Check objects
        const playerBox = new THREE.Box3();
        const center = this.position.clone();
        center.y -= this.capsuleHeight / 2; // Center of body
        playerBox.setFromCenterAndSize(center, new THREE.Vector3(1, 2, 1));

        for (let obj of collidables) {
            const box = new THREE.Box3().setFromObject(obj);
            if (playerBox.intersectsBox(box)) {
                // Vertical collision (standing on top)
                if (this.position.y > box.max.y && this.velocity.y <= 0) {
                     this.position.y = box.max.y + this.capsuleHeight;
                     this.velocity.y = 0;
                     this.canJump = true;
                }
                // Horizontal collision (walls) - simplified pushback
                else {
                    // Very basic push out - fine for prototype feel
                    // Ideal: separate axis resolution
                }
            }
        }

        // Jump
        if (this.keys.space && this.canJump) {
            this.velocity.y = config.jumpForce;
            this.canJump = false;
        }
    }
}

// --- WORLD GENERATION ---

class World {
    constructor(scene, region) {
        this.scene = scene;
        this.collidables = [];
        this.roads = []; // { x, z, axis, width }
        this.regenerate(region);
    }

    regenerate(region) {
        // Clear old geometry
        this.collidables.forEach(m => this.scene.remove(m));
        this.collidables = [];
        this.roads = [];

        // Grid Params
        const gridSize = 100;
        const cellSize = 20;

        // Material
        const buildingMat = new THREE.MeshStandardMaterial({
            color: 0x444444,
            roughness: 0.9
        });
        const roadMat = new THREE.MeshStandardMaterial({ color: 0x111111 });

        // Floor
        const floor = new THREE.Mesh(
            new THREE.PlaneGeometry(500, 500),
            new THREE.MeshStandardMaterial({ color: 0x050505 })
        );
        floor.rotation.x = -Math.PI/2;
        this.scene.add(floor);
        this.collidables.push(floor); // Treat floor as collidable for raycasting logic

        // Procedural City Block Generation
        for(let x = -gridSize; x <= gridSize; x += cellSize) {
            for(let z = -gridSize; z <= gridSize; z += cellSize) {

                // Decide: Road or Building?
                // Create a grid pattern: Roads every 2 cells
                const isRoadX = Math.abs(x) % (cellSize * 2) === 0;
                const isRoadZ = Math.abs(z) % (cellSize * 2) === 0;

                if (isRoadX || isRoadZ) {
                    // Road
                    const road = new THREE.Mesh(
                        new THREE.PlaneGeometry(cellSize, cellSize),
                        roadMat
                    );
                    road.rotation.x = -Math.PI/2;
                    road.position.set(x, 0.01, z); // Slightly above floor
                    this.scene.add(road);

                    // Add to traffic grid
                    if(isRoadX) this.roads.push({ x: x, z: z, axis: 'z', width: region.roadWidth });
                    if(isRoadZ) this.roads.push({ x: x, z: z, axis: 'x', width: region.roadWidth });

                } else {
                    // Building
                    const height = Math.random() * (region.buildingHeightRange[1] - region.buildingHeightRange[0]) + region.buildingHeightRange[0];
                    const geo = new THREE.BoxGeometry(cellSize - 2, height, cellSize - 2);
                    const mesh = new THREE.Mesh(geo, buildingMat);
                    mesh.position.set(x, height / 2, z);
                    this.scene.add(mesh);
                    this.collidables.push(mesh);
                }
            }
        }

        // Add NPC placeholders based on region
        // (Simplified: Just a few static boxes for now, traffic is the main dynamic)
    }
}

// --- TRAFFIC SYSTEM (AAA AI) ---

class TrafficSystem {
    constructor(scene, region, roads) {
        this.scene = scene;
        this.cars = [];
        this.regenerate(region, roads);
    }

    regenerate(region, roads) {
        this.cars.forEach(c => this.scene.remove(c));
        this.cars = [];

        const carGeo = new THREE.BoxGeometry(2, 1.5, 4.5);
        const tailLightGeo = new THREE.BoxGeometry(2, 0.2, 0.2);

        // Spawn N cars
        const count = 50 * region.trafficDensity;

        for(let i=0; i<count; i++) {
            // Pick random road segment
            if(roads.length === 0) break;
            const road = roads[Math.floor(Math.random() * roads.length)];

            const color = Math.random() > 0.9 ? 0xffffff : (Math.random() > 0.5 ? 0xcc0000 : 0x111111);
            const car = new THREE.Group();

            const body = new THREE.Mesh(carGeo, new THREE.MeshStandardMaterial({ color: color }));
            body.position.y = 0.75;
            car.add(body);

            // Tail lights (red glow)
            const tail = new THREE.Mesh(tailLightGeo, new THREE.MeshBasicMaterial({ color: 0xff0000 }));
            tail.position.set(0, 1, 2.2);
            car.add(tail);

            // Random Pos on that road segment
            const offset = (Math.random() - 0.5) * 10;

            if (road.axis === 'z') {
                car.position.set(road.x + (Math.random() > 0.5 ? 2 : -2), 0, road.z + offset);
                car.rotation.y = Math.random() > 0.5 ? 0 : Math.PI; // North or South
            } else {
                car.position.set(road.x + offset, 0, road.z + (Math.random() > 0.5 ? 2 : -2));
                car.rotation.y = Math.random() > 0.5 ? Math.PI/2 : -Math.PI/2; // East or West
            }

            car.userData = {
                speed: 0,
                maxSpeed: 10 + Math.random() * 10,
                axis: road.axis
            };

            this.scene.add(car);
            this.cars.push(car);
        }
    }

    update(delta, playerPos) {
        const raycaster = new THREE.Raycaster();
        const forward = new THREE.Vector3();

        this.cars.forEach(car => {
            // Move forward
            car.getWorldDirection(forward);

            // Raycast ahead for obstacles (other cars or player)
            raycaster.set(car.position, forward);
            const hits = raycaster.intersectObjects(this.cars.map(c => c.children[0]).concat([])); // Ideally checks player too

            let targetSpeed = car.userData.maxSpeed;

            if (hits.length > 0 && hits[0].distance < 10) {
                targetSpeed = 0; // Brake!
            }

            // Simple Player Avoidance (Sphere check)
            if (car.position.distanceTo(playerPos) < 8) {
                targetSpeed = 0; // Stop for player
                // Honk logic could go here
            }

            // Accel/Decel
            car.userData.speed += (targetSpeed - car.userData.speed) * delta * 2.0;

            car.position.addScaledVector(forward, car.userData.speed * delta);

            // Loop world (Infinite traffic illusion)
            if (Math.abs(car.position.x) > 100) car.position.x *= -0.95;
            if (Math.abs(car.position.z) > 100) car.position.z *= -0.95;
        });
    }
}

// --- INTERACTION & DIALOGUE ---

class InteractionSystem {
    constructor(camera, scene, game) {
        this.camera = camera;
        this.scene = scene;
        this.game = game;
        this.raycaster = new THREE.Raycaster();
        this.center = new THREE.Vector2(0, 0);

        this.inDialogue = false;
        this.dialogueQueue = [];
        this.dialogueIndex = 0;

        document.addEventListener('keydown', (e) => {
            if(e.key.toLowerCase() === 'e') this.interact();
        });
    }

    update() {
        if(this.inDialogue) return;

        // Scan for interactables
        this.raycaster.setFromCamera(this.center, this.camera);
        // In a real system we'd check against specific NPC meshes.
        // For this demo, we check proximity to implied objective locations or just allow "E" to trigger story if close to a region point.
        // Let's implement a simple distance check to "Story Node" if defined.

        // Narrative Trigger Logic
        const state = WORLD_DATA.narrative.states[this.game.currentState];
        if (state.dialogue && !this.inDialogue) {
             // For prototype: Always allow triggering the next story beat via 'E' if strict conditions met?
             // Or better: Auto-trigger dialogue if it's "Self" (internal monologue)

             if(state.dialogue.length > 0 && state.dialogue[0].speaker === "Self") {
                 this.startDialogue(state.dialogue);
             }
        }
    }

    interact() {
        if(this.inDialogue) {
            this.nextLine();
            return;
        }

        // Check if we can trigger an interaction (e.g. Talk to Anaya)
        const state = WORLD_DATA.narrative.states[this.game.currentState];
        if (state.npc) {
            // Assume we are close enough (World is small)
            this.startDialogue(state.dialogue);
        }
    }

    startDialogue(lines) {
        this.inDialogue = true;
        this.dialogueQueue = lines;
        this.dialogueIndex = 0;
        this.showDialogueUI(true);
        this.updateDialogueText();
    }

    nextLine() {
        this.dialogueIndex++;
        if(this.dialogueIndex >= this.dialogueQueue.length) {
            this.endDialogue();
        } else {
            this.updateDialogueText();
        }
    }

    updateDialogueText() {
        const line = this.dialogueQueue[this.dialogueIndex];
        const ui = document.getElementById('dialogue-text');
        const speaker = document.getElementById('dialogue-speaker');
        if(ui) ui.innerText = line.text;
        if(speaker) speaker.innerText = line.speaker;
    }

    endDialogue() {
        this.inDialogue = false;
        this.showDialogueUI(false);
        this.game.advanceStory();
    }

    showDialogueUI(show) {
        const box = document.getElementById('dialogue-overlay');
        if(box) box.style.display = show ? 'block' : 'none';
    }
}

// Start
window.onload = () => {
    window.game = new Game();
};
